from aoc_cqkh42.year_2024 import day_08
from aoc_cqkh42.year_2024.day_08 import Solution


def test_part_a():
    data = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
    assert Solution(data).part_a() == 14