[tool.isort]
profile = "black"
skip_glob = ["venv/*", "venv11/*"]

[tool.flake8]
inline-quotes = 'double'
literal-inline-quotes = 'double'
requirements-file = "requirements.txt"

[tool.pylint.parameter_documentation]
accept-no-param-doc = false

accept-no-raise-doc = false

accept-no-return-doc = false

accept-no-yields-doc = false

[tool.pytest.ini_options]
addopts = "-p no:warnings"
#filterwarnings = [

#    "error",
#    "ignore::UserWarning",
#    # note the use of single quote below to denote "raw" strings in TOML
#    'ignore:function ham\(\) is deprecated:DeprecationWarning',
#]

[tool.coverage.run]
omit = "*/tests/*"

[tool.pytest.run]
omit = "*/tests/*"

[tool.coverage.report]
omit = "*/tests/*"
skip_empty = true
show_missing = true

[tool.pytest.report]
omit = "*/tests/*"
skip_empty = true
show_missing = true