import pytest

from aoc_cqkh42.year_2025 import day_07


@pytest.fixture
def solution():
    return day_07.Solution(
        """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""")


def test_part_a(solution):
    assert solution.part_a() == 21

def test_part_b(solution):
    assert solution.part_b() == 40